//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrgCnsHme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodPressure
    {
        public int BpID { get; set; }
        public int PersonID { get; set; }
        public short BpSystolic { get; set; }
        public short BpDiastolic { get; set; }
        public Nullable<short> BpPulse { get; set; }
        public System.DateTime BpDateTime { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
