//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrgCnsHme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GM_script_info
    {
        public int id { get; set; }
        public string user { get; set; }
        public string script { get; set; }
        public string url { get; set; }
        public string info { get; set; }
        public System.DateTime date { get; set; }
    }
}
