//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrgCnsHme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GM_shvdbgState
    {
        public int id { get; set; }
        public string pageTitle { get; set; }
        public string url { get; set; }
        public string lastQuery { get; set; }
        public bool inDbgMode { get; set; }
        public Nullable<short> top { get; set; }
        public Nullable<short> left { get; set; }
        public Nullable<short> width { get; set; }
        public Nullable<short> height { get; set; }
        public System.TimeSpan time { get; set; }
    }
}
