//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrgCnsHme.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class scContext : DbContext
    {
        public scContext()
            : base("name=scContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BloodPressure> BloodPressures { get; set; }
        public DbSet<GM_script_info> GM_script_info { get; set; }
        public DbSet<GM_shvdbgState> GM_shvdbgState { get; set; }
        public DbSet<LafollettePressInfo> LafollettePressInfoes { get; set; }
        public DbSet<SpeedDialSite> SpeedDialSites { get; set; }
        public DbSet<Weight> Weights { get; set; }
        public DbSet<Person> Persons { get; set; }
    }
}
