//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrgCnsHme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weight
    {
        public int WeightID { get; set; }
        public int PersonID { get; set; }
        public float WeightInLb { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
